// <auto-generated />
using System;
using DAL.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DAL.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250525214048_AddImageUrlToMovie")]
    partial class AddImageUrlToMovie
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DAL.Models.AgeGroup", b =>
                {
                    b.Property<int>("AgeCode")
                        .HasColumnType("int");

                    b.Property<string>("AgeDescription")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.HasKey("AgeCode")
                        .HasName("PK__AgeGroup__5B97C6189522A6E4");

                    b.ToTable("AgeGroup");
                });

            modelBuilder.Entity("DAL.Models.Category", b =>
                {
                    b.Property<int>("CategoryCode")
                        .HasColumnType("int");

                    b.Property<string>("CategoryDescription")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.HasKey("CategoryCode")
                        .HasName("PK__Category__371BA954161E6948");

                    b.ToTable("Category");
                });

            modelBuilder.Entity("DAL.Models.Customer", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int?>("AgeGroup")
                        .HasColumnType("int");

                    b.Property<string>("FullName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.Property<string>("Gender")
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("char(1)")
                        .IsFixedLength()
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.Property<string>("Phone")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.Property<byte[]>("ProfilePicture")
                        .HasColumnType("varbinary(max)");

                    b.HasKey("UserId")
                        .HasName("PK__Customer__1788CC4CA2F6AA3C");

                    b.HasIndex("AgeGroup");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("DAL.Models.EmailLink", b =>
                {
                    b.Property<int>("LinkId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("LinkID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LinkId"));

                    b.Property<DateTime>("DateCreated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("EmailType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.Property<DateTime?>("ExpirationDate")
                        .HasColumnType("datetime");

                    b.Property<int>("MovieId")
                        .HasColumnType("int")
                        .HasColumnName("MovieID");

                    b.Property<string>("UniqueToken")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    b.Property<int?>("ViewCount")
                        .HasColumnType("int")
                        .HasColumnName("ViewCount");

                    b.Property<int?>("ViewLimit")
                        .HasColumnType("int")
                        .HasColumnName("ViewLimit");

                    b.HasKey("LinkId")
                        .HasName("PK__EmailLin__2D12215556B5F683");

                    b.HasIndex("MovieId");

                    b.HasIndex(new[] { "UniqueToken" }, "IX_EmailLinks_UniqueToken");

                    b.HasIndex(new[] { "UserId" }, "IX_EmailLinks_UserID");

                    b.HasIndex(new[] { "UniqueToken" }, "UQ__EmailLin__64D6B76BBD003BDE")
                        .IsUnique();

                    b.ToTable("EmailLinks");
                });

            modelBuilder.Entity("DAL.Models.EmailLinkClick", b =>
                {
                    b.Property<int>("ClickId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ClickID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClickId"));

                    b.Property<DateTime>("ClickDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<bool?>("Converted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Ipaddress")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("IPAddress")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.Property<int>("LinkId")
                        .HasColumnType("int")
                        .HasColumnName("LinkID");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.HasKey("ClickId")
                        .HasName("PK__EmailLin__F8E74E2EAC1007D4");

                    b.HasIndex(new[] { "LinkId" }, "IX_EmailLinkClicks_LinkID");

                    b.ToTable("EmailLinkClicks");
                });

            modelBuilder.Entity("DAL.Models.EmailTracking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DateClicked")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("DateSent")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.Property<Guid?>("Token")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id")
                        .HasName("PK__EmailTra__3214EC07BD40BFD7");

                    b.ToTable("EmailTracking");
                });

            modelBuilder.Entity("DAL.Models.Movie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AgeCode")
                        .HasColumnType("int");

                    b.Property<int?>("AmountOfViews")
                        .HasColumnType("int");

                    b.Property<decimal?>("BasePrice")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<int?>("CategoryCode")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.Property<decimal?>("ExtraViewPrice")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<decimal?>("ExtraViewerPrice")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<DateOnly?>("FilmProductionDate")
                        .HasColumnType("date");

                    b.Property<int?>("Length")
                        .HasColumnType("int");

                    b.Property<string>("Link")
                        .HasColumnType("nvarchar(max)")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.Property<bool?>("ThereIsWoman")
                        .HasColumnType("bit");

                    b.HasKey("Id")
                        .HasName("PK__Movies__3214EC07627911D3");

                    b.HasIndex("AgeCode");

                    b.HasIndex("CategoryCode");

                    b.ToTable("Movies");
                });

            modelBuilder.Entity("DAL.Models.Order", b =>
                {
                    b.Property<int>("IdOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdOrder"));

                    b.Property<DateTime>("DateOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("IdCustomer")
                        .HasColumnType("int");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<decimal?>("TotalAmount")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("IdOrder")
                        .HasName("PK__Orders__C38F300988E32713");

                    b.HasIndex("IdCustomer");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("DAL.Models.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("MovieId")
                        .HasColumnType("int");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<decimal>("SubTotal")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<int>("ViewCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<int>("ViewerCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.HasKey("Id")
                        .HasName("PK__OrderIte__3214EC070C2FAC08");

                    b.HasIndex("MovieId");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderItems", t =>
                        {
                            t.HasTrigger("trg_CalculateSubTotal_AfterInsertUpdate");

                            t.HasTrigger("trg_UpdateOrderTotalAmount");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("DAL.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.HasKey("Id")
                        .HasName("PK__Role__3214EC0769967814");

                    b.ToTable("Role");
                });

            modelBuilder.Entity("DAL.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DateCreated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AS");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__Users__3214EC07AFEFEC21");

                    b.HasIndex("RoleId");

                    b.HasIndex(new[] { "Email" }, "UQ__Users__A9D10534957378DF")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("DAL.Models.Customer", b =>
                {
                    b.HasOne("DAL.Models.AgeGroup", "AgeGroupNavigation")
                        .WithMany("Customers")
                        .HasForeignKey("AgeGroup")
                        .HasConstraintName("FK__Customers__AgeGr__12FDD1B2");

                    b.HasOne("DAL.Models.User", "User")
                        .WithOne("Customer")
                        .HasForeignKey("DAL.Models.Customer", "UserId")
                        .IsRequired()
                        .HasConstraintName("FK__Customers__UserI__1209AD79");

                    b.Navigation("AgeGroupNavigation");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DAL.Models.EmailLink", b =>
                {
                    b.HasOne("DAL.Models.Movie", "Movie")
                        .WithMany("EmailLinks")
                        .HasForeignKey("MovieId")
                        .IsRequired()
                        .HasConstraintName("FK__EmailLink__Movie__29E1370A");

                    b.HasOne("DAL.Models.Customer", "User")
                        .WithMany("EmailLinks")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK__EmailLink__UserI__28ED12D1");

                    b.Navigation("Movie");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DAL.Models.EmailLinkClick", b =>
                {
                    b.HasOne("DAL.Models.EmailLink", "Link")
                        .WithMany("EmailLinkClicks")
                        .HasForeignKey("LinkId")
                        .IsRequired()
                        .HasConstraintName("FK__EmailLink__LinkI__2EA5EC27");

                    b.Navigation("Link");
                });

            modelBuilder.Entity("DAL.Models.Movie", b =>
                {
                    b.HasOne("DAL.Models.AgeGroup", "AgeCodeNavigation")
                        .WithMany("Movies")
                        .HasForeignKey("AgeCode")
                        .HasConstraintName("FK__Movies__AgeCode__16CE6296");

                    b.HasOne("DAL.Models.Category", "CategoryCodeNavigation")
                        .WithMany("Movies")
                        .HasForeignKey("CategoryCode")
                        .HasConstraintName("FK__Movies__Category__15DA3E5D");

                    b.Navigation("AgeCodeNavigation");

                    b.Navigation("CategoryCodeNavigation");
                });

            modelBuilder.Entity("DAL.Models.Order", b =>
                {
                    b.HasOne("DAL.Models.Customer", "IdCustomerNavigation")
                        .WithMany("Orders")
                        .HasForeignKey("IdCustomer")
                        .IsRequired()
                        .HasConstraintName("FK__Orders__IdCustom__1C873BEC");

                    b.Navigation("IdCustomerNavigation");
                });

            modelBuilder.Entity("DAL.Models.OrderItem", b =>
                {
                    b.HasOne("DAL.Models.Movie", "Movie")
                        .WithMany("OrderItems")
                        .HasForeignKey("MovieId")
                        .IsRequired()
                        .HasConstraintName("FK__OrderItem__Movie__22401542");

                    b.HasOne("DAL.Models.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .IsRequired()
                        .HasConstraintName("FK__OrderItem__Order__214BF109");

                    b.Navigation("Movie");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("DAL.Models.User", b =>
                {
                    b.HasOne("DAL.Models.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .IsRequired()
                        .HasConstraintName("FK__Users__RoleId__0E391C95");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("DAL.Models.AgeGroup", b =>
                {
                    b.Navigation("Customers");

                    b.Navigation("Movies");
                });

            modelBuilder.Entity("DAL.Models.Category", b =>
                {
                    b.Navigation("Movies");
                });

            modelBuilder.Entity("DAL.Models.Customer", b =>
                {
                    b.Navigation("EmailLinks");

                    b.Navigation("Orders");
                });

            modelBuilder.Entity("DAL.Models.EmailLink", b =>
                {
                    b.Navigation("EmailLinkClicks");
                });

            modelBuilder.Entity("DAL.Models.Movie", b =>
                {
                    b.Navigation("EmailLinks");

                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("DAL.Models.Order", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("DAL.Models.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("DAL.Models.User", b =>
                {
                    b.Navigation("Customer");
                });
#pragma warning restore 612, 618
        }
    }
}
